export enum API_URL {
  ADMIN_LOGIN = "/admin/adminLogin",
  ADMIN_PROFILE_DATA = "/admin/loginData",
  ADMIN_LOGOUT = "/general/logout",
  ADMIN_PROFILE_FORM = "/admin/profileFormData",
  COMPLETE_PROFILE = "/admin/completeProfile",
  ADMIN_PROFILE_VIEW = "/admin/profileViewData",
  ADMIN_PROFILE_PIC_UPDATE = "/admin/updateProfilePic",
  CREATE_ADMIN = "/admin/createAdmin",
  GET_ALL_ADMINS = "/admin/allAdmins",
  CREATE_ATC = "/atc/createATC",
  GET_ALL_ATC = "/atc/allATC",
  CHANGE_ATC_STATUS = "/atc/updateStatus/:id",
  CHANGE_ADMIN_STATUS = "/admin/updateStatus/:id",
  EDIT_ATC_BY_ID = "/atc/edit/:id",
  GET_ATC_BY_ID = "/atc/:id",
  GET_MANAGER_BY_ATC_ID = "/manager/atcID",
  EDIT_MANAGER_BY_ID = "/manager/edit/:id",
  GET_ALL_MANAGER = "/manager/",
  CHANGE_MANAGER_STATUS = "/manager/status/:id",
  GET_DASHBOARD_DATA = "/admin/dashboard",

  APPROVE_TRAINING = "/admin/approve/:id",
  GET_ALL_TRAINING = "/admin/viewAll",
  GET_SPECIFIC_TRAINING = "/general/:trainingId",
  GET_ATC_SPECIFIC_TRAINING = "/admin/training/:id",

  GET_YEARLY_INFO = "/admin/info",
  ADD_YEARLY_INFO = "/admin/yearlyInfo",
}
