import { Request, Response, NextFunction } from "express";
import { StudentModel } from "../../../models/student.model";
import { ErrorResponse, ErrorType } from "../../../utils/customError";
import { jsonResponse } from "../../../utils/jsonResponse";

export const verifyCertificateById = async (
  req: Request,
  res: Response,
  next: NextFunction
) => {
  const studentId = req.params.studentId;
  const student = await StudentModel.findById(studentId).select(
    "name email trainingId studentCollegeName _id"
  );
  if (!student) {
    return next(
      new ErrorResponse(
        ErrorType.BAD_REQUEST,
        "Invalid Certificate",
        "We could not verify this request, It's invalid and was not generated by authorized system"
      )
    );
  }
  return jsonResponse(res, {
    status: "success",
    statusCode: 200,
    data: student,
    title: "Certificate Validated",
  });
};
